global:
  rclone:
    paths:
      conf_file: /etc/quadrumane/rclone.cfg
      log_dir: /opt/logs
    options:
      checksum: switch_arg
      fast-list: switch_arg
      create-empty-src-dirs: switch_arg
      ignore-errors: switch_arg
      s3-upload-cutoff: 0
      progress: switch_arg
      metadata: switch_arg
      multi-thread-streams: 12
      transfers: 12
      checkers: 14
      exclude: "/.tt_rt/**"
    providers:
      wasabi: WasabiRessource
      aws: AWSRessource
jobs:
  - title: "Dossier trop bien"
    type: sync
    source: wasabi
    target: aws
    min_age_days: 1
    max_age_days: 2
    create_subfolder: true
    buckets:
      wasabi: "bucket_trop_bien"
      aws: "backup_bucket_trop_bien"
  - title: "Un autre super dossier"
    type: sync
    source: wasabi
    target: aws
    min_age_days: 1
    max_age_days: 2
    create_subfolder: true
    buckets:
      wasabi: "autre_bucket_de_ouf"
      aws: "backup_autre_bucket_de_ouf"
